### ISSUE TITLE
Mockup design of website

### ISSUE THREAD

**Issue by garymuff** [garymuff/POSproject#12]
Make a static base design of the website. Functionality not necessary. Make acceptance tests and to do's on the scrum board

**Comment by imzhang1** [comment]
**Acceptance Test**
- User can go to openpos.herokuapp.com.  
- User can locate logo on the top of the page.
- User can locate the menu bar that is under the logo.
- User can locate the number keypad, under the menu bar.
- User can locate the dynamic receipt, next to the number keypad.
- User can locate the "My Inventory" section, bottom of the page.
- User can type into the search bar for the inventory count. 
- User can locate the four columns in "My Inventory, labeled "Product Name", "SKU", "Price", "Count".
- User can locate the footer at the bottom of the page.
