### ISSUE TITLE
Inventory page

### ISSUE THREAD

**Issue by aliofye** [garymuff/POSproject#14]
As a manager, I want to be able to see all of my products on one page

**Comment by imzhang1** [comment]
**Acceptance Test**

- Manager can go to http://openpos.herokuapp.com/inventory.html.
- Manager can locate title on the top of the page.
- Manager can locate the filter menu bar under title.
- Manager can locate the items listed on the screen.
- Manager can locate the picture of the item listed.
- Manager can open a modal pop-up when they click on an item.
- Manager can locate the header of the modal (title) in the modal.
- Manager can locate the body of the modal (price,inventory count) in the modal.
- Manager can locate the footer of the modal (SKU) in the modal.
- Manager can click on the 'x' to close the modal.
- Manager can click outside the modal to close the modal.

**Comment by imzhang1** [comment]
**Acceptance Test**
- Manager will have the inventory button on the header of the page.
- When manager goes to the inventory page, manager should be able to see all of his/her items listed.
- When manager hovers over one of their items, the sku, price, item count, and "delete item" button will appear over their item.
