### ISSUE TITLE
Redesign the homepage and add more colors

### ISSUE THREAD

**Issue by aliofye** [garymuff/POSproject#46]
We need to add more flair to the homepage, we are going with a BLACK/GOLD color pallette so please try to use that. You can safely remove the inventory table that @imzhang1 did because I'm creating a new page for that.

**Comment by garymuff** [comment]
task46 complete. Main page redesigned to look and feel of login page. Utilized gold and black color scheme. Inventory table removed and removed Receipt for redesign.
