### ISSUE TITLE
Design inventory page

### ISSUE THREAD

**Issue by aliofye** [garymuff/POSproject#48]
Initial design of the inventory page

**Comment by aliofye** [comment]
Done!

**Comment by garymuff** [comment]
Inventory needs CSS fix for centering the body.

**Comment by garymuff** [comment]
Successfully added a div container to wrap the content and center it appropriately.

**Comment by garymuff** [comment]
**Test:**
- On page load, items will appear on the webpage
- Cashier clicks on item, then dialog box appears with that items information.
- Cashier clicks the (x) or outside the dialog prompt and it then disappears.
