### ISSUE TITLE
Dynamic reciept

### ISSUE THREAD

**Issue by aliofye** [garymuff/POSproject#64]
As a cashier, I want to see the items that I scanned show up dynamically on the screen

**Comment by garymuff** [comment]
**Acceptance Test**

 - Cashier will use Number Pad to enter 6 digit SKU, after clicking the green checkmark. The SKU and other data relating to the SKU will populate (line by line).

 - Cashier will provide multiple entries that exceed the height of the container, then container will add scroll bar for scrolling long list.
