### ISSUE TITLE
Add navigation bar to Inventory page.

### ISSUE THREAD

**Issue by garymuff** [garymuff/POSproject#70]
Add navigation bar to Inventory page, similar to the one on the main page

**Comment by garymuff** [comment]
Let's use the same design elements. You should be able to copy the header divs from the index.html and tag the header.css file to the page and it should bring in all the design elements from the index.html. We may have to move the box design class to the header.css file though to get the box around the menu.

**Comment by imzhang1** [comment]
**Test**

Click on inventory page button from any page and you can see the navigation bar on the inventory page.
