### ISSUE TITLE
Implement cart checkout.

### ISSUE THREAD

**Issue by garymuff** [garymuff/POSproject#71]
As a cashier, I would like to checkout my customer with a checkout button/process.

**Comment by imzhang1** [comment]
**Acceptance Test**
- Cashier will not be able to see the checkout button until an item is added to the dynamic receipt.
- Cashier will be able to click on the checkout button when finished with entering items into the receipt for the customer. 
- Cashier will be able to locate the total amount in the checkout pop-up.
- Cashier will be able to click on the cash button and the message "Payment Successful!" will come up. 
- Cashier will be able to enter another transaction now that the receipt is cleared after the last payment was successful.
