### ISSUE TITLE
Automatically clear numpad

### ISSUE THREAD

**Issue by imzhang1** [garymuff/POSproject#79]
automatically clear the number pad after a value is entered into the receipt

**Comment by garymuff** [comment]
This issue was resolved in Task67 - Backspace for Numberpad.

**Comment by garymuff** [comment]
**Test:**
- Enter a SKU, then click the green check mark to submit.
- If accepted the display will clear the SKU value and post the item to the receipt container.
- If it is unaccepted it will display an error and not post or clear the value.
