### ISSUE TITLE
Add quantity buttons to the number pad

### ISSUE THREAD

**Issue by imzhang1** [garymuff/POSproject#80]
Add an "+" and "-" buttons to number pad or add a "change quantity" button feature that allows for the number pad to change the quatity by selecting the number of items.

**Comment by garymuff** [comment]
**Test:**
- Cashier clicks (+) button then QTY input will increase by 1
- Cashier clicks (-) button then QTY input will decrease by 1
- The (+) button will become in active once the user reaches QTY 99
- The (-) button will become in active once the user reaches QTY 1
- Cashier clicks Clear / (✗) button on the number pad, QTY will reset to 1
- Cashier clicks Submit / (✓) button on the number pad, QTY will reset to 1
